//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("1.0.17184.1927")]
[assembly: AssemblyFileVersion("1.0.17184.1927")]
[assembly: AssemblyInformationalVersion("1.0.17184.1927")]

