//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("1.1.19347.1205")]
[assembly: AssemblyFileVersion("1.1.19347.1205")]
[assembly: AssemblyInformationalVersion("1.1.19347.1205")]

