//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.Edgerunner.FluentGuard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Org.Edgerunner.FluentGuard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be equal to {0}.
        /// </summary>
        internal static string MustBeEqualToX {
            get {
                return ResourceManager.GetString("MustBeEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than or equal to {0}.
        /// </summary>
        internal static string MustBeGreaterThanOrEqualToX {
            get {
                return ResourceManager.GetString("MustBeGreaterThanOrEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than {0}.
        /// </summary>
        internal static string MustBeGreaterThanX {
            get {
                return ResourceManager.GetString("MustBeGreaterThanX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than or equal to {0}.
        /// </summary>
        internal static string MustBeLessThanOrEqualToX {
            get {
                return ResourceManager.GetString("MustBeLessThanOrEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than {0}.
        /// </summary>
        internal static string MustBeLessThanX {
            get {
                return ResourceManager.GetString("MustBeLessThanX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must end with {0}.
        /// </summary>
        internal static string MustEndWithX {
            get {
                return ResourceManager.GetString("MustEndWithX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be null.
        /// </summary>
        internal static string MustNotBeNull {
            get {
                return ResourceManager.GetString("MustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be null or empty.
        /// </summary>
        internal static string MustNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("MustNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must start with {0}.
        /// </summary>
        internal static string MustStartWithX {
            get {
                return ResourceManager.GetString("MustStartWithX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is null or empty..
        /// </summary>
        internal static string ValueIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ValueIsNullOrEmpty", resourceCulture);
            }
        }
    }
}
