//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NDepend.Attributes;

namespace Org.Edgerunner.FluentGuard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
#if NDEPEND
      [UncoverableByTest]
#endif
      internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Org.Edgerunner.FluentGuard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
#if NDEPEND
         [UncoverableByTest]
#endif
         get
         {
                return resourceCulture;
            }
#if NDEPEND
         [UncoverableByTest]
#endif
         set
         {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be equal to {0}.
        /// </summary>
        internal static string MustBeEqualToX {
            get {
                return ResourceManager.GetString("MustBeEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be false.
        /// </summary>
        internal static string MustBeFalse {
            get {
                return ResourceManager.GetString("MustBeFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than or equal to {0}.
        /// </summary>
        internal static string MustBeGreaterThanOrEqualToX {
            get {
                return ResourceManager.GetString("MustBeGreaterThanOrEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than {0}.
        /// </summary>
        internal static string MustBeGreaterThanX {
            get {
                return ResourceManager.GetString("MustBeGreaterThanX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must be an interface.
        /// </summary>
        internal static string MustBeInterface {
            get {
                return ResourceManager.GetString("MustBeInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than or equal to {0}.
        /// </summary>
        internal static string MustBeLessThanOrEqualToX {
            get {
                return ResourceManager.GetString("MustBeLessThanOrEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than {0}.
        /// </summary>
        internal static string MustBeLessThanX {
            get {
                return ResourceManager.GetString("MustBeLessThanX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be negative.
        /// </summary>
        internal static string MustBeNegative {
            get {
                return ResourceManager.GetString("MustBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be null.
        /// </summary>
        internal static string MustBeNull {
            get {
                return ResourceManager.GetString("MustBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be of type {0}.
        /// </summary>
        internal static string MustBeOfType {
            get {
                return ResourceManager.GetString("MustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be positive.
        /// </summary>
        internal static string MustBePositive {
            get {
                return ResourceManager.GetString("MustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be the same instance.
        /// </summary>
        internal static string MustBeSameAs {
            get {
                return ResourceManager.GetString("MustBeSameAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be true.
        /// </summary>
        internal static string MustBeTrue {
            get {
                return ResourceManager.GetString("MustBeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must end with {0}.
        /// </summary>
        internal static string MustEndWithX {
            get {
                return ResourceManager.GetString("MustEndWithX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must implement interface {0}.
        /// </summary>
        internal static string MustImplementInterface {
            get {
                return ResourceManager.GetString("MustImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must inherit type {0}.
        /// </summary>
        internal static string MustInheritType {
            get {
                return ResourceManager.GetString("MustInheritType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be empty.
        /// </summary>
        internal static string MustNotBeEmpty {
            get {
                return ResourceManager.GetString("MustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be equal to {0}.
        /// </summary>
        internal static string MustNotBeEqualToX {
            get {
                return ResourceManager.GetString("MustNotBeEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be negative.
        /// </summary>
        internal static string MustNotBeNegative {
            get {
                return ResourceManager.GetString("MustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be null.
        /// </summary>
        internal static string MustNotBeNull {
            get {
                return ResourceManager.GetString("MustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be positive.
        /// </summary>
        internal static string MustNotBePositive {
            get {
                return ResourceManager.GetString("MustNotBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must start with {0}.
        /// </summary>
        internal static string MustStartWithX {
            get {
                return ResourceManager.GetString("MustStartWithX", resourceCulture);
            }
        }
    }
}
